server:
  port: '${AUTH_SERVER_PORT:8010}'
  address: 0.0.0.0

spring:
  application:
    name: oauth2authorizationserver

  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}'

    username: '${POSTGRES_USERNAME}'
    password: '${POSTGRES_PASSWORD}'
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    show-sql: true

  liquibase:
    change-log: 'classpath:db/changelog/changelog-main.yaml'

  config:
    import: 'classpath:keystore.yaml,classpath:client.yaml'


logging:
  level:
    ru.manannikov.oauth2authorizationserver: DEBUG
    org.springframework.security: TRACE

  pattern.console: '%d{dd.MM.yyyy HH:mm:ss} [%t] %-5level %c{10} %M --> %msg%n'


springdoc:
  group-configs:
    - group: security
      packages-to-scan: "ru.manannikov.oauth2authorizationserver.controllers"
      paths-to-match: "/test"